### ISSUE TITLE
Button formatting on mobile

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/declaring-independence#30]
On mobile buttons:
* don't have any verticle padding: https://declaring-independence.org/why-open-access-and-why-now
* don't adjust to screen width e.g: https://declaring-independence.org/is-your-journal-right-for-open-access

Would be good to adjust this

**Comment by markmacgillivray** [comment]
Added 5px margin-bottom to button class in _sass/components/_button.scss

Added 10px padding top and bottom

Removed heights and line-heights, apart from default top level button line-height of 2em (was 3.5)



Changed layout of the buttons themselves in the content page
is-your-journal-right-for-open-access.md
and

**Comment by JosephMcArthur** [comment]
Both of these look fixed, but, now there is something that looks _weird_ for a reason I can't explain. They used to look slick, now they look dumb. Hard to say why, but judging by the originals it's due to a lack of padding: https://www.dropbox.com/s/r6hj6nc0lce6l5z/Screenshot%202018-06-11%2018.15.06.png?dl=0 

Why did you adjust line height, which I suppose is what did this?

**Comment by markmacgillivray** [comment]
Because on other pages you have put really long content into buttons, and they were overflowing off the page, so I had to change buttons to not have a fixed height and to allow their content to run onto multiple lines. But with a large line height this results in really big buttons on mobile with too much space between the lines of text in each button.

I'm not sure what you're referring to looking weird, the buttons still look fine to me.

**Comment by JosephMcArthur** [comment]
Gotcha. They're likely fine, and I'm just used to the old ones. Will close.
