### ISSUE TITLE
references have become huge (should be normal text size)

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/declaring-independence#31]
https://declaring-independence.org/why-open-access-and-why-now

**Comment by markmacgillivray** [comment]
Added font-size:1em into a p tag inside the ol li definition in _sass/components/_list.scss because the markdown renderer is turning the footnotes into para tags inside li tags, causing the normal para font size and the li font size to be applied. Now that para font size is back to 1, the li paras created by the markdown rendering of footnotes come out the same size as other text
